services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - ./.env
        ports:
            - 3000:3000
    mysql:
        image: mysql:latest
        env_file:
            - ./.env
        ports:
            - 3306:3306
